DO $$ BEGIN CREATE DOMAIN QUESTION_ID CHAR(21);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN QUESTION VARCHAR(300) CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN ANSWER TEXT CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN VIEWS INT CHECK (VALUE >= 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS questions (
	id QUESTION_ID NOT NULL PRIMARY KEY,
	question QUESTION NOT NULL UNIQUE,
	answer ANSWER, -- NULL if not answered
	related QUESTION[], -- NULL if not found related questions
	views VIEWS NOT NULL DEFAULT 0,
	created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
